"""
Contract tests for the ImageGridSeedream workflow.

ImageGridSeedream generates a 3x3 editorial grid from a single reference image,
rendering the final grid with ByteDance Seedream and cropping it into 9 cells
plus a stitched output.
"""
import pytest
import json


@pytest.mark.workflow
@pytest.mark.asyncio
class TestImageGridSeedreamWorkflowContract:
    """Contract tests for ImageGridSeedream workflow"""

    WORKFLOW_NAME = "ImageGridSeedream"

    REQUIRED_PARAMS = {
        "IMAGE_FILENAME",
        "SUBJECT_PROMPT_PREFIX",
        "APPENDED_PROMPT",
        "SEED_1",
        "SEED_2",
    }

    VALID_TEST_PARAMS = {
        "IMAGE_FILENAME": "reference.png",
        "SUBJECT_PROMPT_PREFIX": "Broad category chosen by user: product. ",
        "APPENDED_PROMPT": "moody cinematic lighting. ",
        "SEED_1": 123456789,
        "SEED_2": 987654321,
    }

    async def test_workflow_file_exists(self, workflows_dir):
        """Test that the workflow JSON file exists"""
        workflow_path = workflows_dir / f"{self.WORKFLOW_NAME}.json"
        assert workflow_path.exists(), f"{self.WORKFLOW_NAME}.json must exist"

    async def test_all_parameters_documented(self, workflow_service):
        """Test that all documented parameters are actually used in the workflow"""
        success, params, error = await workflow_service.get_template_parameters(
            self.WORKFLOW_NAME
        )

        assert success is True, f"Failed to extract parameters: {error}"
        assert set(params) == self.REQUIRED_PARAMS, \
            f"Parameter mismatch. Expected: {self.REQUIRED_PARAMS}, Found: {set(params)}"

    async def test_builds_with_valid_params(self, workflow_service):
        """Test that workflow builds successfully with valid parameters"""
        success, workflow, error = await workflow_service.build_workflow(
            self.WORKFLOW_NAME,
            self.VALID_TEST_PARAMS
        )

        assert success is True, f"Failed to build workflow: {error}"
        assert workflow is not None
        assert error is None

    async def test_no_unsubstituted_placeholders(self, workflow_service):
        """Test that all placeholders are substituted"""
        success, workflow, _ = await workflow_service.build_workflow(
            self.WORKFLOW_NAME,
            self.VALID_TEST_PARAMS
        )

        assert success is True

        workflow_str = json.dumps(workflow)
        # Only check for "{{" — a bare "}}" occurs legitimately wherever two JSON
        # objects close consecutively, so it is not a reliable placeholder signal.
        assert "{{" not in workflow_str, "Found unsubstituted placeholders"

    async def test_validates_successfully(self, workflow_service):
        """Test that built workflow passes validation"""
        success, workflow, _ = await workflow_service.build_workflow(
            self.WORKFLOW_NAME,
            self.VALID_TEST_PARAMS
        )

        assert success is True

        is_valid, validation_error = await workflow_service.validate_workflow(workflow)
        assert is_valid is True, f"Workflow validation failed: {validation_error}"

    async def test_has_output_node(self, workflow_service):
        """Test that workflow has an output node (SaveImage)"""
        success, workflow, _ = await workflow_service.load_template(self.WORKFLOW_NAME)

        assert success is True

        output_node_types = ["SaveImage", "SaveVideo", "VHS_VideoCombine", "PreviewImage"]
        has_output = any(
            node_data.get("class_type") in output_node_types
            for node_data in workflow.values()
        )

        assert has_output, \
            f"Workflow must have an output node (types: {', '.join(output_node_types)})"

    async def test_uses_seedream_node(self, workflow_service):
        """Test that the final image is generated by the ByteDance Seedream node"""
        success, workflow, _ = await workflow_service.load_template(self.WORKFLOW_NAME)
        assert success is True

        class_types = [node_data.get("class_type") for node_data in workflow.values()]
        assert "ByteDanceSeedreamNode" in class_types, \
            "ImageGridSeedream must use ByteDanceSeedreamNode for the final grid"
