"""
RunPod Handler Template for ComfyUI Workflows

This is a TEMPLATE showing how handlers are structured when generated via comfy.getrunpod.io.
DO NOT deploy this template directly - use comfy.getrunpod.io to generate workflow-specific handlers.

How to create a handler for your workflow:
1. Export your workflow JSON from ComfyUI (e.g., backend/workflows/VideoLipsync.json)
2. Go to https://comfy.getrunpod.io/
3. Upload your workflow JSON
4. Click "Generate Handler" button
5. Download the generated handler.py
6. Deploy to RunPod serverless with Network Volume
7. Add endpoint ID to backend/config/runpod_endpoints.py
8. Set environment variable: RUNPOD_ENDPOINT_<WORKFLOW_NAME>=your-endpoint-id

Example generated handler structure:
"""

import runpod
import json
import requests
from typing import Dict, Any

# ComfyUI server URL (running in the same pod)
COMFYUI_URL = "http://127.0.0.1:8188"


def execute_comfyui_workflow(workflow: Dict[str, Any], input_params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute ComfyUI workflow with given parameters.

    This function is auto-generated by comfy.getrunpod.io based on your workflow.
    It knows which nodes need which parameters and how to substitute them.

    Args:
        workflow: The ComfyUI workflow structure (embedded in handler)
        input_params: Runtime parameters from API request

    Returns:
        Dictionary with output files (images/videos)
    """
    # Example: The generated handler will have logic like this:
    # workflow["node_1"]["inputs"]["image"] = input_params["image_filename"]
    # workflow["node_2"]["inputs"]["prompt"] = input_params["prompt"]
    # workflow["node_3"]["inputs"]["width"] = input_params.get("width", 640)
    # ... etc for all parameters

    # Submit workflow to ComfyUI
    response = requests.post(
        f"{COMFYUI_URL}/prompt",
        json={"prompt": workflow}
    )

    if response.status_code != 200:
        raise Exception(f"ComfyUI error: {response.status_code}")

    prompt_id = response.json()["prompt_id"]

    # Poll for completion
    while True:
        history = requests.get(f"{COMFYUI_URL}/history/{prompt_id}").json()

        if prompt_id in history:
            outputs = history[prompt_id].get("outputs", {})

            # Extract output files (structure depends on workflow)
            result_files = []
            for node_id, node_output in outputs.items():
                if "images" in node_output:
                    for img in node_output["images"]:
                        # Download file from ComfyUI
                        file_url = f"{COMFYUI_URL}/view?filename={img['filename']}&type=output"
                        file_data = requests.get(file_url).content

                        result_files.append({
                            "filename": img["filename"],
                            "data": file_data,  # or base64.b64encode(file_data).decode()
                            "type": "image"
                        })

            return {"files": result_files, "status": "COMPLETED"}


def handler(event: Dict[str, Any]) -> Dict[str, Any]:
    """
    RunPod handler function - entry point for serverless execution.

    This is the function that RunPod calls when a job is submitted.
    Auto-generated by comfy.getrunpod.io.

    Args:
        event: RunPod event with 'input' containing parameters

    Returns:
        Dictionary with 'output' containing results
    """
    try:
        # Extract input parameters
        input_params = event.get("input", {})

        # The workflow structure is embedded in the generated handler
        # (comfy.getrunpod.io bakes it into the handler code)
        workflow = {
            # Workflow structure here...
            # This is auto-generated based on your uploaded workflow
        }

        # Execute workflow with parameters
        result = execute_comfyui_workflow(workflow, input_params)

        return {
            "output": result,
            "status": "COMPLETED"
        }

    except Exception as e:
        return {
            "error": str(e),
            "status": "FAILED"
        }


# RunPod serverless initialization
if __name__ == "__main__":
    runpod.serverless.start({"handler": handler})
